### ISSUE TITLE
results!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [wiz64/saavn-web-ui#2]
woowwwwwwww amazing job!but please could you make it increase unlimited results?its not fair shows just so few!!!

**Comment by wiz64** [comment]
> 
Hello @KENPOKASMMA1982 
I have been inactive for a really long time since now due to a lot of personal problems, anyway, I am back now, and will soon re-write it from scratch. well a lot of users complained about the UI, so i will fix that part as well..
Thanks for trying this out !

**Comment by KENPOKASMMA1982** [comment]
woowwwwwwwwwwwwwww....Wiz I am begging youuuuuuuuuuuuuuuuuu make your unbelievable web increase unlimited results....pleaseeeeeeeeeeeee my friend!!!

**Comment by KENPOKASMMA1982** [comment]
my friend hello...tell me please now increase unlimited results?

**Comment by KENPOKASMMA1982** [comment]
my friend check has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by wiz64** [comment]
one can increase results by looking out for other artists in fetched songs, currently the saavn.me is in development and as its developers extend it, features will improve..
and The CORS Policy can be fixed easy, just fork the repo, deploy your own instance on vercel or netlify, that will offer the most flexibility.
This site as in its current state was developed 2 years ago and I will have to rewrite it from scratch,
If anyone can help with the UI, I would appreciate that :-)

**Comment by KENPOKASMMA1982** [comment]
my good friend for more results just you need one botton load more!for the cors I dont know how to make it I am sorry!I hope you make one update very soon.GOD BLESS YOU MY FRIEND!!!

**Comment by KENPOKASMMA1982** [comment]
MY GOOD FRIEND SAAVN PAGE HAS DOWN?WHY STILL DONT WORKS YOUR AMAZING PROJECT!!!

**Comment by wiz64** [comment]
> MY GOOD FRIEND SAAVN PAGE HAS DOWN?WHY STILL DONT WORKS YOUR AMAZING PROJECT!!!

The original api is down as its faced some attacks recently, we do have a forked api, I updated it to https://github.com/saavn-cli yesterday, i've just update it to this repo as well

**Comment by KENPOKASMMA1982** [comment]
WOOWWWW...MY GOOD FRIEND PLEASE ADD ONE BOTTON LOAD MORE ON YOUR AMAZING PROJECT...PLEASE DUDE!!!

**Comment by wiz64** [comment]
> WOOWWWW...MY GOOD FRIEND PLEASE ADD ONE BOTTON LOAD MORE ON YOUR AMAZING PROJECT...PLEASE DUDE!!!

You can contact me thru https://wiz64.com.
Write to me in DMs so i can understand in detail.
I'll add up the summary here

**Comment by wiz64** [comment]
added in v2.2
