### ISSUE TITLE
load more!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [wiz64/saavn-web-ui#7]
my friend congratulations for the update....but I am begging you could you make one botton load more?or un scroll infinity?pleaseeeeeeeeeeeeeee!!!

**Comment by wiz64** [comment]
well. you could just reply on the old thread..
I'm on it.. coming soon, just a bit busy recently, i would be implementing more features (such as albums, artists, playlists)
I'll add load more first on your request :-) 
also, try out the download feature !

**Comment by KENPOKASMMA1982** [comment]
wooww....you are amazing my friend!but tell me you will make it load more today?pleaseeeeeeeee man!!!

**Comment by wiz64** [comment]
I am currently busy with studies as my exams are near :| 
don't worry I will do it as soon as possible and as i get a break..

**Comment by wiz64** [comment]
> woowwwww....ok my friend!!!I wish you good luck and all the best my friend!I hope you will make it as soon as possible!my best regards!!!(PLEASE I AM BEGGING YOU IF YOU CAN OFCOURSE COULD YOU MAKE IT SEARCH LIKE THIS 2022 LOVE POP AND APPEAR ONLY THE SONGS WITH TITLE LOVE WHERE RELEASED 2022 WITH GENRE ONLY POP)IT WOULD BE GREATTTTTTTTTTTTTTTT MY FRIEND!!!

I was just trying that, I'll need to according to new API, I guess its not worth it, I better create a new player from scratch and implement features like that..

**Comment by KENPOKASMMA1982** [comment]
wiz my friend thanks so much...and I am begging you because original web increase many duplicate results...please try remove all the duplicate results!!!

JIOSAAVN HAVE A NICE WEEK...PLEASE AMAZING SAAVN FIX THE BIG PROBLEM WITH THE SAME RESULTS 🙁

Hey Panos, thanks for your patience and thank you so much for sending us all the details so far, we really appreciate it. We're working on this, please hang in there and we'll get back to you the minute we have an update.

**Comment by wiz64** [comment]
> HELLO MY FRIEND AND MERRY CHRISTMAS TO YOU AND YOUR FAMILY!TELL ME PLEASE ANY UPDATE SOON WITH LOAD MORE RESULTS AND WITHOUT DUPLICATE RESULTS???

I'm on a full-from-scratch update... busy as usual, but I'm on it

**Comment by KENPOKASMMA1982** [comment]
OK MY FRIEND!!!I HOPE UNTILL THIS WEEK YOU WILL UPDATE IT!THANKS SO MUCH!!!!!!!!!

**Comment by wiz64** [comment]
> OK MY FRIEND!!!I HOPE UNTILL THIS WEEK YOU WILL UPDATE IT!THANKS SO MUCH!!!!!!!!!

you can also try : https://app.saavn.me

**Comment by wiz64** [comment]
@KENPOKASMMA1982  Done ! I have added the "load more" button as you requested :-)
Enjoy !!! I did this as i thought implementing a new UI from scratch would take a lot of time so I just added to the current one.
I'm sorry for delaying it. I can't do anything about the duplicate results tbh, they exist on saavn severs as well and there are many tracks with same names and albums over minimal changes. 
Have a nice day.

**Comment by KENPOKASMMA1982** [comment]
thankssssssssssssss so muchhhhhhhhhhh!!but tell me please this with so many duplicate results its up only from jiosaavn servers?are you sure my friend?

**Comment by KENPOKASMMA1982** [comment]
> https://app.saavn.me

woowwwwww....amazingggggggg!!!but my friend this is amazing web for unlimited results!!!I hope you make one load more !!!

**Comment by wiz64** [comment]
> > https://app.saavn.me
> 
> woowwwwww....amazingggggggg!!!but my friend this is amazing web for unlimited results!!!I hope you make one load more !!!

try https://saavn-web-ui.vercel.app/ or https://saavn.codeforkers.tk/
I just added it

**Comment by KENPOKASMMA1982** [comment]
my friend yes I know!!!I mean if you can add it on this amazing update https://app.saavn.me/

**Comment by KENPOKASMMA1982** [comment]
Wiz my good friend do you believe that you can add load more on your amazing update just for now?pleaseeeeeeee my friend!if you can of course!!!

**Comment by wiz64** [comment]
> Wiz my good friend do you believe that you can add load more on your amazing update just for now?pleaseeeeeeee my friend!if you can of course!!!

I do not own https://app.saavn.me

**Comment by KENPOKASMMA1982** [comment]
> > Wiz my good friend do you believe that you can add load more on your amazing update just for now?pleaseeeeeeee my friend!if you can of course!!!
> 
> I do not own https://app.saavn.me

ohhhhh I am sorry my good friend!I thought that is yours!!!aaaaa ok Wiz!really tell me please api permit search music by genre also?for example love pop or amor latin etc

**Comment by wiz64** [comment]
> > > Wiz my good friend do you believe that you can add load more on your amazing update just for now?pleaseeeeeeee my friend!if you can of course!!!
> > 
> > 
> > I do not own https://app.saavn.me
> 
> ohhhhh I am sorry my good friend!I thought that is yours!!!aaaaa ok Wiz!really tell me please api permit search music by genre also?for example love pop or amor latin etc

I don't think the api contains any data relating to genres..

**Comment by KENPOKASMMA1982** [comment]
> > > > Wiz my good friend do you believe that you can add load more on your amazing update just for now?pleaseeeeeeee my friend!if you can of course!!!
> > > 
> > > 
> > > I do not own https://app.saavn.me
> > 
> > 
> > ohhhhh I am sorry my good friend!I thought that is yours!!!aaaaa ok Wiz!really tell me please api permit search music by genre also?for example love pop or amor latin etc
> 
> I don't think the api contains any data relating to genres.. Saavn itself doesn't do that..

what a pity my friend but its ok!!!

**Comment by wiz64** [comment]
Okay, thanks for being interested in my repository, you can support me through https://wiz64.com/sponsor so that i can spend more of precious time developing open source stuff.
You can close this issue, I'll create a new player from scratch with optimised code, minimal bloatware and open source ofc, that should supports searching by artists, albums, playlists etc.
at https://github.com/wiz64/Libermusic
star the repo as well :-)

**Comment by KENPOKASMMA1982** [comment]
> Okay, thanks for being interested in my repository, you can support me through https://wiz64.com/sponsor so that i can spend more of precious time developing open source stuff. You can close this issue, I'll create a new player from scratch with optimised code, minimal bloatware and open source ofc, that should supports searching by artists, albums, playlists etc. at https://github.com/wiz64/Libermusic star the repo as well :-)

thats nice my friend!thanks so much for your amazing web and projects!!!I ll be waiting for your new update!!!good day!
