### ISSUE TITLE
songs not playing

### ISSUE THREAD

**Issue by djsaikrishna** [wiz64/saavn-web-ui#8]
plz check

**Comment by wiz64** [comment]
Thanks for pointing it out 👍🏻 
I will fix this as soon as possible (2 days i guess, as i have exams)
The problem : old api endpoints are now depreciated, as a result it gets a 404 and has nothing to load/play.
need to do some major changes.

**Comment by wiz64** [comment]
Thank you! I've updated the API and it works again now.

**Comment by djsaikrishna** [comment]
🔥

**Comment by wiz64** [comment]
> 🔥

updated UI as well, within a few days will add many more features
